swagger:
  enabled: true
  name: lwjppz
  email: lwjppz@gmail.com
  url: https://www.lwjppz.cn
  title: 用户服务
  base-package: cn.lwjppz.mindstorm.auth.controller
  version: V2.0
  description: 用户服务
  license: Apache License, Version 2.0
  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  terms-of-service-url: http://localhost:7000/doc.html