POST http://localhost:9000/education/question/import
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="importFile"; filename="importQuestion.xls"

< C:\Users\lwj\Desktop\importQuestion.xls
--WebAppBoundary--

###
###
GET http://localhost:9000/education/question/info/1419658558586736642
Accept: application/json
Cache-Control: no-cache
