spring:
  datasource:
    username: root
    password: LWJLWJ20000829
    url: jdbc:mysql://localhost:3306/mindstorm-knowledge?useUnicode=true&characterEncoding=utf-8&useSSL=true
    &serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    # 连接池的配置信息
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:cn/lwjppz/mindstorm/permission/mapper/xml/*.xml

swagger:
  enabled: true
  name: lwjppz
  email: lwjppz@gmail.com
  url: https://www.lwjppz.cn
  title: 用户服务
  base-package: cn.lwjppz.mindstorm.permission.controller
  version: V2.0
  description: 用户服务
  license: Apache License, Version 2.0
  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  terms-of-service-url: http://localhost:7000/doc.html