### 获取知识点树
GET {{ideaBaseUrl}}/tree
Accept: application/json
Cache-Control: no-cache

### 新增知识点
POST {{ideaBaseUrl}}/create
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
  "pid": "1401371653541519361",
  "name": "文言文子知识点的子知识点",
  "description": "测试子知识点的子知识点",
  "sort": 1
}

### 根据知识点Id获取知识点信息
GET {{ideaBaseUrl}}/info/1401370854522368001
Accept: application/json
Cache-Control: no-cache

### 更新知识点
POST {{ideaBaseUrl}}/update
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
  "id": "1401370854522368001",
  "name": "文言文",
  "description": "这是一种古文，很难理解的那种。",
  "sort": 2
}

### 根据知识点Id删除知识点
DELETE {{ideaBaseUrl}}/delete/1401370854522368001
Accept: application/json
Cache-Control: no-cache
