### 所有学科信息
GET {{subjectBaseUrl}}/list
Accept: application/json
Cache-Control: no-cache

### 根据年级获取学科信息
GET {{subjectBaseUrl}}/listByLevel?level=12
Accept: application/json
Cache-Control: no-cache

### 新建学科
POST {{subjectBaseUrl}}/create
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache

{
  "name": "数学",
  "level": 1,
  "description": "数学学科"
}

### 分页学科信息
GET {{subjectBaseUrl}}/page/1/5
Accept: application/json
Cache-Control: no-cache

### 根据学科Id获取学科信息
PUT {{subjectBaseUrl}}/info?subjectId=1400752240392003586
Accept: application/json
Cache-Control: no-cache

### 更新学科信息
POST {{subjectBaseUrl}}/update
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache

{
  "id": "1400752240392003586",
  "name": "语文",
  "level": 1,
  "description": "这是语文学科"
}

### 根据学科Id删除学科信息
DELETE {{subjectBaseUrl}}/delete/1400752240392003586
Accept: application/json
Cache-Control: no-cache

### 根据学科Id集合删除学科信息
DELETE {{subjectBaseUrl}}/deleteBatch
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

["1400819775363739650", "1400820891950284801"]