server:
  port: 9000

spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

  application:
    name: mindstorm-permission

  profiles:
    active: dev

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:cn/lwjppz/mindstorm/permission/mapper/xml/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

swagger:
  enabled: true
  name: lwjppz
  email: lwjppz@gmail.com
  url: https://www.lwjppz.cn
  title: 用户服务
  base-package: cn.lwjppz.mindstorm.permission.controller
  version: V2.0
  description: 用户服务
  license: Apache License, Version 2.0
  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  terms-of-service-url: http://localhost:7000/doc.html
